//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.DanhMucs = new HashSet<DanhMuc>();
            this.KhoHangs = new HashSet<KhoHang>();
            this.ChiTietHangHoas = new HashSet<ChiTietHangHoa>();
            this.PhanQuyenNguoiDungs = new HashSet<PhanQuyenNguoiDung>();
            this.CongNoes = new HashSet<CongNo>();
            this.DonHangs = new HashSet<DonHang>();
            this.ThuChis = new HashSet<ThuChi>();
            this.KhachHangs = new HashSet<KhachHang>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ThanhToanCongNoes = new HashSet<ThanhToanCongNo>();
        }
    
        private long _id;
    	public long Id 
    	{ 
    		get { return _id; } 
    		set
    		{
    			if (value != _id) {
    				_id = value;
    				 OnPropertyChanged("Id");
    			}
    		} 
    	}
    
        private Nullable<long> _createdDate;
    	public Nullable<long> CreatedDate 
    	{ 
    		get { return _createdDate; } 
    		set
    		{
    			if (value != _createdDate) {
    				_createdDate = value;
    				 OnPropertyChanged("CreatedDate");
    			}
    		} 
    	}
    
        private Nullable<long> _modifiedDate;
    	public Nullable<long> ModifiedDate 
    	{ 
    		get { return _modifiedDate; } 
    		set
    		{
    			if (value != _modifiedDate) {
    				_modifiedDate = value;
    				 OnPropertyChanged("ModifiedDate");
    			}
    		} 
    	}
    
        private bool _isActived;
    	public bool IsActived 
    	{ 
    		get { return _isActived; } 
    		set
    		{
    			if (value != _isActived) {
    				_isActived = value;
    				 OnPropertyChanged("IsActived");
    			}
    		} 
    	}
    
        private string _tenNguoiDung;
    	public string TenNguoiDung 
    	{ 
    		get { return _tenNguoiDung; } 
    		set
    		{
    			if (value != _tenNguoiDung) {
    				_tenNguoiDung = value;
    				 OnPropertyChanged("TenNguoiDung");
    			}
    		} 
    	}
    
        private string _matKhau;
    	public string MatKhau 
    	{ 
    		get { return _matKhau; } 
    		set
    		{
    			if (value != _matKhau) {
    				_matKhau = value;
    				 OnPropertyChanged("MatKhau");
    			}
    		} 
    	}
    
        private string _loaiNguoiDung;
    	public string LoaiNguoiDung 
    	{ 
    		get { return _loaiNguoiDung; } 
    		set
    		{
    			if (value != _loaiNguoiDung) {
    				_loaiNguoiDung = value;
    				 OnPropertyChanged("LoaiNguoiDung");
    			}
    		} 
    	}
    
        private string _tenNhanVien;
    	public string TenNhanVien 
    	{ 
    		get { return _tenNhanVien; } 
    		set
    		{
    			if (value != _tenNhanVien) {
    				_tenNhanVien = value;
    				 OnPropertyChanged("TenNhanVien");
    			}
    		} 
    	}
    
        private string _diaChi;
    	public string DiaChi 
    	{ 
    		get { return _diaChi; } 
    		set
    		{
    			if (value != _diaChi) {
    				_diaChi = value;
    				 OnPropertyChanged("DiaChi");
    			}
    		} 
    	}
    
        private string _cMND;
    	public string CMND 
    	{ 
    		get { return _cMND; } 
    		set
    		{
    			if (value != _cMND) {
    				_cMND = value;
    				 OnPropertyChanged("CMND");
    			}
    		} 
    	}
    
        private string _dienthoai;
    	public string Dienthoai 
    	{ 
    		get { return _dienthoai; } 
    		set
    		{
    			if (value != _dienthoai) {
    				_dienthoai = value;
    				 OnPropertyChanged("Dienthoai");
    			}
    		} 
    	}
    
        private string _ghiChu;
    	public string GhiChu 
    	{ 
    		get { return _ghiChu; } 
    		set
    		{
    			if (value != _ghiChu) {
    				_ghiChu = value;
    				 OnPropertyChanged("GhiChu");
    			}
    		} 
    	}
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoHang> KhoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHangHoa> ChiTietHangHoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyenNguoiDung> PhanQuyenNguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNo> CongNoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuChi> ThuChis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToanCongNo> ThanhToanCongNoes { get; set; }
    }
}
