IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DBO' AND TABLE_NAME = 'DonHang' AND COLUMN_NAME = 'TyGia')
BEGIN	
	ALTER TABLE DBO.DonHang 
	ADD TyGia BigInt NOT NULL
	CONSTRAINT DF_DonHang_TyGia DEFAULT(1) 
END