IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DBO' AND TABLE_NAME = 'ChiTietDonHang' AND COLUMN_NAME = 'GiaNhap')
BEGIN	
	ALTER TABLE DBO.ChiTietDonHang 
	ADD GiaNhap bigint
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DBO' AND TABLE_NAME = 'KhoHang' AND COLUMN_NAME = 'GiaNhap')
BEGIN	
	ALTER TABLE DBO.KhoHang 
	ADD GiaNhap bigint
END

exec ADD_DEFAULT_CONSTRAINT 'ChiTietDonHang', 'GiaNhap', '0', 'bigint'
exec ADD_DEFAULT_CONSTRAINT 'KhoHang', 'GiaNhap', '0', 'bigint'


CREATE INDEX INDEX_ChiTietHangHoa_IMEI ON ChiTietHangHoa (IMEI);


